"""Post-commit git hook that links commits to Claude Code sessions."""

from __future__ import annotations

import logging
import subprocess
import textwrap
from datetime import datetime, timedelta, timezone
from pathlib import Path

from hive.config import Config
from hive.store.query import QueryAPI

logger = logging.getLogger(__name__)


class GitCommitHook:
    """Creates edges between git commits and recently-active sessions.

    When invoked as a post-commit hook the flow is:

    1. Read the commit SHA and changed file list from git.
    2. Find the most recently ended session within the configured
       ``link_window_minutes`` window.
    3. Create *edges* that link the session to the commit and to each
       changed file.
    """

    def __init__(self, config: Config | None = None) -> None:
        self._config = config or Config.load()
        self._api = QueryAPI(self._config)

    # ── Public API ───────────────────────────────────────────────────

    def run(self, repo_path: str | None = None) -> bool:
        """Execute the post-commit logic.

        Parameters
        ----------
        repo_path:
            Working directory of the repository.  Defaults to the
            current directory.

        Returns
        -------
        bool
            ``True`` if an edge was created, ``False`` otherwise.
        """
        repo_path = repo_path or "."

        commit_sha = _git_output(["git", "rev-parse", "HEAD"], cwd=repo_path)
        if not commit_sha:
            logger.warning("Could not determine HEAD commit SHA.")
            return False

        session = self._find_recent_session()
        if session is None:
            logger.debug("No recent session found within the link window.")
            return False

        session_id: str = session["id"]

        # Link session -> commit.
        try:
            self._api.insert_edge(
                source_type="session",
                source_id=session_id,
                target_type="commit",
                target_id=commit_sha,
                relationship="produced",
            )
        except Exception:
            logger.debug("Edge session->commit already exists (skipped).")

        # Link session -> each changed file.
        changed_files = _changed_files_in_commit(commit_sha, cwd=repo_path)
        for fp in changed_files:
            try:
                self._api.insert_edge(
                    source_type="session",
                    source_id=session_id,
                    target_type="file",
                    target_id=fp,
                    relationship="committed",
                )
            except Exception:
                logger.debug("Duplicate edge session=%s file=%s (skipped).", session_id, fp)

        logger.info(
            "Linked session %s to commit %s (%d files).",
            session_id,
            commit_sha[:10],
            len(changed_files),
        )
        return True

    # ── Hook script generation ───────────────────────────────────────

    @staticmethod
    def generate_hook_script() -> str:
        """Return the shell script content for ``.git/hooks/post-commit``.

        The generated script invokes hive's CLI entry-point so
        that the hook runs in the user's Python environment.
        """
        return textwrap.dedent(
            """\
            #!/usr/bin/env bash
            # Generated by hive — do not edit manually.
            # Links git commits to the most recently active AI session.

            if command -v hive &>/dev/null; then
                hive hook post-commit &
            fi
            """
        )

    def install_hook(self, repo_path: str) -> Path:
        """Write the post-commit hook script into the given repository.

        Parameters
        ----------
        repo_path:
            Root of the git repository.

        Returns
        -------
        Path
            Absolute path to the installed hook file.

        Raises
        ------
        FileNotFoundError
            If ``repo_path`` does not contain a ``.git`` directory.
        """
        hooks_dir = Path(repo_path) / ".git" / "hooks"
        if not hooks_dir.parent.is_dir():
            raise FileNotFoundError(f"No .git directory found in {repo_path}")

        hooks_dir.mkdir(parents=True, exist_ok=True)
        hook_path = hooks_dir / "post-commit"

        # Preserve any existing hook by appending rather than replacing.
        if hook_path.exists():
            existing = hook_path.read_text(encoding="utf-8")
            if "hive" in existing:
                logger.info("Hook already installed at %s", hook_path)
                return hook_path
            # Append our invocation after the existing content.
            with hook_path.open("a", encoding="utf-8") as fh:
                fh.write("\n# --- hive post-commit hook ---\n")
                fh.write("if command -v hive &>/dev/null; then\n")
                fh.write("    hive hook post-commit &\n")
                fh.write("fi\n")
        else:
            hook_path.write_text(self.generate_hook_script(), encoding="utf-8")

        hook_path.chmod(0o755)
        logger.info("Installed post-commit hook at %s", hook_path)
        return hook_path

    # ── Internal helpers ─────────────────────────────────────────────

    def _find_recent_session(self) -> dict | None:
        """Return the most recently ended session within the link window."""
        window = self._config.link_window_minutes
        cutoff = (datetime.now(timezone.utc) - timedelta(minutes=window)).isoformat()

        sessions = self._api.list_sessions(since=cutoff, limit=1)
        if not sessions:
            return None

        return sessions[0]


# ── Module-level git helpers ─────────────────────────────────────────


def _git_output(cmd: list[str], cwd: str = ".") -> str:
    """Run a git command and return stripped stdout, or empty string on failure."""
    try:
        proc = subprocess.run(
            cmd,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if proc.returncode == 0:
            return proc.stdout.strip()
    except (OSError, subprocess.TimeoutExpired):
        pass
    return ""


def _changed_files_in_commit(sha: str, cwd: str = ".") -> list[str]:
    """Return the list of file paths changed in the given commit."""
    output = _git_output(
        ["git", "diff-tree", "--no-commit-id", "--name-only", "-r", sha],
        cwd=cwd,
    )
    if not output:
        return []
    return [line.strip() for line in output.splitlines() if line.strip()]
